/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  mySidebar: [
    {
      type: 'html',
      value: 'OVERVIEW',
      className: 'sidebar-title-first',
    },
    {
      type: 'doc',
      id: 'overview/introduction',
      label: 'Introduction'
    },
    {
      type: 'html',
      value: 'RESOURCES',
      className: 'sidebar-title',
    },
    {
      type: 'doc',
      id: 'resources/repositories',
      label: 'Repositories'
    },
    {
      type: 'doc',
      id: 'resources/official-links',
      label: 'Official Links'
    },
    {
      type: 'html',
      value: 'DEVELOPERS',
      className: 'sidebar-title',
    },
    {
      type: 'doc',
      id: 'developers/connecting-to-bitcoinzk',
      label: 'Connecting to BitcoinZK'
    }
   ]
};

export default sidebars;
