/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  mySidebar: [
    {
      type: "html",
      value: "General",
      className: "sidebar-title-first",
    },
    {
      type: "doc",
      id: "general/About BitcoinZK",
      label: "About BitcoinZK",
    },
    {
      type: "doc",
      id: "general/Key Features",
      label: "Key Features",
    },
    {
      type: "doc",
      id: "general/FAQs",
      label: "FAQs",
    },
    {
      type: "html",
      value: "Learn",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "resources/L2 for Bitcoin",
      label: "L2 for Bitcoin",
    },
    {
      type: "doc",
      id: "resources/Zero-knowledge",
      label: "Zero-Knowledge",
    },
    {
      type: "doc",
      id: "resources/Rollup Architecture",
      label: "Rollup Architecture",
    },
    {
      type: "doc",
      id: "resources/ZK Asset Bridge",
      label: "ZK Asset Bridge",
    },
    {
      type: "html",
      value: "Use",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "resources/Deposit",
      label: "Deposit BTC",
    },
    {
      type: "doc",
      id: "resources/Withdraw",
      label: "Withdraw BTC",
    },
    {
      type: "html",
      value: "Build",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "resources/repositories",
      label: "Repositories",
    },
    {
      type: "doc",
      id: "developers/connecting-to-bitcoinzk",
      label: "Connecting to BitcoinZK",
    },
  ],
};

export default sidebars;
